export const CREATE_EXERCISE = 'GET_EXERCISE';
export const UPDATE_EXERCISE = 'SET_EXERCISE';

export const UPDATE_TYPED_TEXT = 'UPDATE_TYPED_TEXT';

export const UPDATE_MISTAKE_INDEXES = 'UPDATE_MISTAKE_INDEXES';

export const INITIALIZE_UNFIXED_MISTAKES = 'export const INITIALIZE_UNFIXED_MISTAKES';
export const UPDATE_UNFIXED_MISTAKES = 'UPDATE_UNFIXED_MISTAKES';

export const UPDATE_TIMESTAMP = 'UPDATE_TIMESTAMP';
export const CLEAR_TIMESTAMPS = 'CLEAR_TIMESTAMPS';
